### ISSUE TITLE
stargazer doesn't work

### ISSUE THREAD

**Issue by maravento** [nastyox/Repo-Roster#11]
stargazer by https://reporoster.com is down or does not work with the proposed configuration

example: 

### doesn't work:

code:
```
[![Stargazers repo roster for @nastyox/Repo-Roster](https://reporoster.com/stars/nastyox/Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)
```
out:

[![Stargazers repo roster for @nastyox/Repo-Roster](https://reporoster.com/stars/nastyox/Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)

### works:

code:

```
[![Stargazers repo roster for @nastyox/Repo-Roster](https://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=nastyox&repo=Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)
```
out:

[![Stargazers repo roster for @nastyox/Repo-Roster](https://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=nastyox&repo=Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)

Please fix it. thk

**Comment by dmitriy-chernysh** [comment]
The same to me. It seems the issue is in SSL certificate that was expired

**Comment by dmitriy-chernysh** [comment]
I've just replaced https by http here `https://reporoster.com/` and it works now

**Comment by maravento** [comment]
No. check code with https doesn't work:
```
[![Stargazers repo roster for @nastyox/Repo-Roster](https://reporoster.com/stars/nastyox/Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)
```

out

[![Stargazers repo roster for @nastyox/Repo-Roster](https://reporoster.com/stars/nastyox/Repo-Roster)](https://github.com/nastyox/Repo-Roster/stargazers)

**Comment by dhondta** [comment]
@nastyox FYI ; SSL certificate is expired since 25/10/23. Move to Let's Encrypt ?...

**Comment by walidbosso** [comment]
Actually you guys should use `http`, I copied the code normally, but removed ` 's' ` and it worked @dmitriy-chernysh @dhondta @maravento 
```
[![Stargazers repo roster for @walidbosso/Java_Task_Scheduling](http://reporoster.com/stars/walidbosso/Java_Task_Scheduling)](https://github.com/walidbosso/Java_Task_Scheduling/stargazers)```

**Comment by walidbosso** [comment]
@dmitriy-chernysh @dhondta @maravento Do you guys have any similar service provider but for general `followers` this time?

**Comment by nastyox** [comment]
Resolved
