### ISSUE TITLE
Can we add contributors in the same way?

### ISSUE THREAD

**Issue by yash982000** [nastyox/Repo-Roster#2]

**Comment by yash982000** [comment]
If we plan or there is a way, please let me know as I am interested in working on this feature.

**Comment by nastyox** [comment]
Watchers, contributors, and followers are next on my list. If you'd like to work on this and submit a pull request, please feel free to do so. If not, feel free to wait for a release from me! Thanks for your interest in the project!

**Comment by nastyox** [comment]
It's been long enough. This is not my current priority, so I'm going to leave this up to whomever wants to submit a well-done pull request for it. Thanks!
