### ISSUE TITLE
Are there customization options?

### ISSUE THREAD

**Issue by Andre601** [nastyox/Repo-Roster#3]
Title says it all. Can the image be customised to display differently?

For example, can it be changed to only display the avatars in such a way?
![image](https://user-images.githubusercontent.com/11576465/118358923-43edd200-b581-11eb-86aa-680bf31b3cac.png)

If that isn't a thing, could it be considered, since the white background looks really of when using dark-themed GitHub.

**Comment by nastyox** [comment]
Sure! 

For normal styling use a URL like this:
https://reporoster.com/stars/nastyox/Repo-Roster

For dark mode, just add "/dark" into the URL, like this:
https://reporoster.com/stars/dark/nastyox/Repo-Roster

To remove text, add "/notext" into the URL, like this:
https://reporoster.com/stars/notext/nastyox/Repo-Roster

To combine the two, add both into the URL, like this:
https://reporoster.com/stars/dark/notext/nastyox/Repo-Roster

--------OR--------
You can do this all with our tool at:
https://reporoster.com/

**Comment by Andre601** [comment]
Could you implement a mode to remove the background altogether?
The white but also the dark mode background kinda conflict with cases where you f.e. use dark mode on websites.

A prime example would be the Readme file where the image may look good on light-theme, but bad on dark theme and vice-versa.

Additionally would I say that it would be more readable and easy to use, when you just have query-parameters rather than URL sections.

Examples:
- https://reporoster.com/stars/dark/nastyox/Repo-Roster `->` https://reporoster.com/stars/nastyox/Repo-Roster?style=dark
- https://reporoster.com/stars/notext/nastyox/Repo-Roster `->` https://reporoster.com/stars/nastyox/Repo-Roster?text=hide
- https://reporoster.com/stars/dark/notext/nastyox/Repo-Roster `->` https://reporoster.com/stars/nastyox/Repo-Roster?style=dark&text=hide

The benefit of this would be that you wouldn't need to handle X paths for each text and style combination but rather just check for provided query parameters.
Of course this is just me talking and I have no real idea about how difficult this would actually be to make and handle with the language this is made in.

**Comment by nastyox** [comment]
I can't prioritize this right now. But while it sits on my to-do list, the code is public in this repository. You are welcome to do the work and submit a pull request. Thanks!
