### ISSUE TITLE
show more avatars

### ISSUE THREAD

**Issue by raminious** [nastyox/Repo-Roster#4]
hey there,

is it possible to make it customizable to show more than four avatars?

**Comment by wj-Mcat** [comment]
it seems that `max_show_starts` is fixed to 4, you can check it out to the [code](https://github.com/nastyox/Repo-Roster/blob/34d1fd2160cab37796eff40a60272bcea2d16f21/code/stars.php#L8)

**Comment by nastyox** [comment]
Yes! Please feel free to host the code yourself if you're willing to dedicate more resources towards that than we are. Thank you.
