### ISSUE TITLE
It seems to be down

### ISSUE THREAD

**Issue by atapas** [nastyox/Repo-Roster#5]
I see the images are coming broken since the last few days.

![image](https://user-images.githubusercontent.com/3633137/179751995-4542df91-2c45-4786-8c26-4c4d4c9d265c.png)

**Comment by nastyox** [comment]
Thank you for letting me know! I'll look into this and get back to you about a solution.

**Comment by nastyox** [comment]
Resolved. Thanks again for letting me know!
